DROP TABLE IF EXISTS SHORT_URL;
CREATE TABLE SHORT_URL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LINK VARCHAR(1023) NOT NULL,
  STATUS INTEGER NOT NULL,
  createdAt TIMESTAMP NOT NULL default now(),
  PRIMARY KEY (ID)
);